routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', 'StaticPagesController@home')->name('home');
Route::get('/help', 'StaticPagesController@help')->name('help');
Route::get('/about', 'StaticPagesController@about')->name('about');
Route::get('/feature', 'StaticPagesController@feature')->name('feature');

Route::get('signup', 'UsersController@create')->name('signup');
Route::resource('users', 'UsersController');

//登录、退出
Route::get('login', 'SessionsController@create')->name('login');
Route::post('login', 'SessionsController@store')->name('login');
Route::delete('logout', 'SessionsController@destroy')->name('logout');

//注册邮箱验证
Route::get('signup/confirm/{token}', 'UsersController@confirmEmail')->name('confirm_email');

//修改密码
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::resource('statuses', 'StatusesController', ['only' => ['store', 'destroy']]);

resources/views/layouts/_footer.blade.php
<div class="col-md-12">
    <footer class="footer">
        <small class="slogon">
            <img class="brand-icon" src="https://lccdn.phphub.org/uploads/images/201612/12/1/iq7WQc2iuW.png?imageView2/1/w/34/h/34">
            <a href="https://laravel-china.org/courses">
                刻意练习，每日精进
            </a>
        </small>
        <nav>
            <ul>
                <li><a href="{{ route('about') }}">关于</a></li>
            </ul>
        </nav>
    </footer>
</div>

<script>
    $(function () {
        var height = $(window).height(),
            main = $('main'),
            header = $('.header'),
            footer = $('.footer'),
            total = main.innerHeight() + header.innerHeight() + footer.innerHeight();

        if (total < height) {
            footer.css({'margin-top': (height - total) + 'px'});
        }
    });
</script>

resources/views/layouts/_header.blade.php
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="col-md-offset-1 col-md-10">
            <a href="/" id="logo">
                <img src="/images/logo/logo.gif" title="首页" style="width: 7%;height: auto;">
            </a>
            {{--<div class="top_search">
                <input type="text" placeholder="Search...">
                <div class="search"></div>
            </div>--}}
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    @if (Auth::check())
                        <li><a href="{{ route('users.index') }}">用户列表</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                {{ Auth::user()->name }} <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ route('users.show', Auth::user()->id) }}">个人中心</a></li>
                                <li><a href="{{ route('users.edit', Auth::user()->id) }}">编辑资料</a></li>
                                <li class="divider"></li>
                                <li>
                                    <a id="logout" href="#">
                                        <form action="{{ route('logout') }}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-block btn-danger" type="submit" name="button">退出</button>
                                        </form>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    @else
                        <li><a href="{{ route('help') }}">帮助</a></li>
                        <li><a href="{{ route('login') }}">登录</a></li>
                    @endif
                        <li><a href="{{ route('feature') }}">Features</a></li>
                        <li><a href="{{ route('about') }}">关于页</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>@yield('title', 'Zero Web')</title>
        <link rel="stylesheet" href="/css/app.css">
        <link rel="stylesheet" href="/css/pointer.css">

        <script src="/css/font.css"></script>
        {{--<script src="/css/fountain.css"></script>--}}
        <script src="/css/rain.css"></script>
        {{--<script src="/css/slider.css"></script>--}}
        {{--<script src="/css/prism.css"></script>--}}
    </head>
    <body>
    @include('layouts._header')
    <div class="container">
        <div class="col-md-offset-1 col-md-10">
            @include('shared._messages')
            @yield('content')
            @include('layouts._footer')
        </div>
    </div>

    <script src="/js/app.js"></script>
    <script src="/js/font.js"></script>
    <script src="/js/rain.js"></script>
    {{--<script src="/js/beerslider.js"></script>--}}
    {{--<script src="/js/prism.js"></script>--}}

    {{--<script src="/js/pointer.js"></script>--}}
    {{--<script src="/js/fountain.js"></script>--}}

    </body>
</html>